export {default as Header} from './Header/Header'
export {default as Banner} from './Banner/Banner'
export {default as Catalog} from './Catalog/Catalog'
export {default as Cart} from './Cart/Cart'
export {default as Product} from './Product/Product'
export {default as Slider} from './Swiper/Swiper'
export {default as Collection} from './Collection/Collection'
export {default as Footer} from './Footer/Footer'